# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180125_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
